apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-identity-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: identity-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: identity-service
