apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rheosim-db-credentials
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    DB_ROOT_PASSWORD: AgA...
    DB_PASSWORD: AgA...
  template:
    metadata:
      name: rheosim-db-credentials
      namespace: {{ .Values.global.namespace }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rheosim-jwt-keypair
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    private.pem: AgA...
    public.pem: AgA...
  template:
    metadata:
      name: jwt-keypair
      namespace: {{ .Values.global.namespace }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rheosim-redis-credentials
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    REDIS_PASSWORD: AgA...
  template:
    metadata:
      name: rheosim-redis-credentials
      namespace: {{ .Values.global.namespace }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rheosim-minio-credentials
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    MINIO_PASSWORD: AgA...
  template:
    metadata:
      name: rheosim-minio-credentials
      namespace: {{ .Values.global.namespace }}
    type: Opaque
